version: "3.4"

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: secure-t-test-task
    restart: unless-stopped
    entrypoint: bash -c "sleep 5 && uvicorn --factory main:App.get_app --host 0.0.0.0 --port 8080 --reload"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8080:8080"
